### ISSUE TITLE
Double Framed IP Address attribute in Reply Attributes Edit user

### ISSUE THREAD

**Issue by Mindless999** [lirantal/daloradius#309]
Currently it looks like you will have a double listing of Framed-IP-Address when set.
Top one you can delete, and it will delete for both, but changing will not change it
bottom one will not delete when pressing the button, but when changing it will change them both.

Not sure if this is a incorrect listing or if something else is going strange.

It only is with Framed-IP-Address, and it doesn't matter if you add it first, or later

![image](https://user-images.githubusercontent.com/20699783/207578806-97454bd6-79bb-46b4-af4d-a7c5c9fcfa54.png)

**Comment by filippolauria** [comment]
As long as I could have tested, it seems to me that the issue has been addressed in #312

**Comment by Mindless999** [comment]
I will take a look tomorrow, and see if it will have fixed it.

**Comment by Mindless999** [comment]
It looks like it still shows up double.

Note it looks like it's specific to "Framed-IP-Address" and not other attributes (so far).

**Comment by filippolauria** [comment]
What you see is not one attribute shown as a double: in your db, in the table reply, you already have two identical attributes for this user (except for the id field).
You can try to edit/delete one of this. The action should not affect the other.

**Comment by Mindless999** [comment]
If I add this record once, it will show up as double.
If I edit the top one, nothing happens
If I edit the bottom one, both change
If I delete the top one both are deleted
If I delete the bottom one nothing happens

all of these symptoms point to me, that for some reason it displays double. 

Also when I do a `select * from radreply;` on the mysql, I okly see one record for the user with the `Framed-IP-Address`

Example:
```
select * from radreply where username = 'test-2';
+-----+----------+-------------------+----+---------------+
| id  | username | attribute         | op | value         |
+-----+----------+-------------------+----+---------------+
| 249 | test-2   | Framed-IPv6-Pool  | =  | 192.168.123.1 |
| 251 | test-2   | Framed-IP-Address | =  | 192.168.1.1   |
+-----+----------+-------------------+----+---------------+
```

I still will see double the Framed-IP-Address:
![image](https://user-images.githubusercontent.com/20699783/207873035-6b867e31-7ff0-4c04-ae4c-27bc379eed17.png)

**Comment by filippolauria** [comment]
Ok. I've recreated your exact scenario:
```
select * from radreply where username='test-2';
+----+----------+-------------------+----+---------------+
| id | username | attribute         | op | value         |
+----+----------+-------------------+----+---------------+
| 19 | test-2   | Framed-IP-Address | =  | 192.168.1.1   |
| 20 | test-2   | Framed-IPv6-Pool  | =  | 192.168.123.1 |
+----+----------+-------------------+----+---------------+
```
But still cannot figure out what is going on your side.
![image](https://user-images.githubusercontent.com/4223503/207892224-cabfa378-98fe-4296-aff2-4330f0478cc7.png)

Try update again your instance with the current master branch code.

**Comment by Mindless999** [comment]
Strange, I re downloaded the entire code, (new git clone) and it still does as the way I have shown it.

is there a way to find out what query is used to get the information, to make sure that this is also giving the expected result on the database?

I am unable to figure out the reason why this could be happening.

**Comment by Mindless999** [comment]
It looks like this is the issue, for some reason I have double values for the recommendedTooltip value.

not sure what or why but if you can point me in the correct direction I will take a look!
Thank you so far! (see query below) 

```
 SELECT rr.attribute, rr.op, rr.value, dd.type, dd.recommendedTooltip, rr.id FROM radreply AS rr LEFT JOIN dictionary AS dd ON rr.attribute = dd.attribute AND dd.value IS NULL WHERE rr.username='test-2' ORDER BY rr.id ASC;
+-------------------+----+---------------+--------+---------------------------------------------------------------------+-----+
| attribute         | op | value         | type   | recommendedTooltip                                                  | id  |
+-------------------+----+---------------+--------+---------------------------------------------------------------------+-----+
| Framed-IPv6-Pool  | =  | 192.168.123.1 | string | NULL                                                                | 249 |
| Framed-IP-Address | =  | 192.168.1.1   | ipaddr |                                                                     | 251 |
| Framed-IP-Address | =  | 192.168.1.1   | ipaddr | This Attribute indicates the address to be configured for the user. | 251 |
+-------------------+----+---------------+--------+---------------------------------------------------------------------+-----+

```

**Comment by filippolauria** [comment]
Yeah. In a future commit, I will try to implement a check when adding new attributes in the dictionary.
