### ISSUE TITLE
New User (Based on MAC address)

### ISSUE THREAD

**Issue by dleventidis** [lirantal/daloradius#403]
Hello,

when i'm trying to create a New User Based on MAC address (to implement cisco mab) i can't put the mac address without colons between pairs (e.g. 00AABBCCDDEE) the NAS sends the MAC using this format.

**Comment by filippolauria** [comment]
Hello @dleventidis ,
thanks for your feedback.
What you reported has been addressed in #409.

**Comment by dleventidis** [comment]
Sorry, but the issue is still there. I have installed via git clone https://github.com/lirantal/daloradius.git but the issue is stil there.

**Comment by dleventidis** [comment]
On the file mng-new.php line: 68 if i remove the ,FILTER_VALIDATE_MAC then it works.
filter_var(trim(strtoupper($_POST['macaddress'])),FILTER_VALIDATE_MAC)) ? trim(strtoupper($_POST['macaddress'])) : "";

But when i list users the icon with the ethernet is missing and the pin icon is displayed instead.

Reagrds

**Comment by filippolauria** [comment]
With #421, this issue should have been fixed.

**Comment by dleventidis** [comment]
confirmed!
