### ISSUE TITLE
Duplicate entry '252' for key 'PRIMARY'

### ISSUE THREAD

**Issue by prabath84** [lirantal/daloradius#486]
Hi All,

Today I am trying to install FreeRadius + DaloRadius in Debian 11.
I'm getting this error right now. 

**ERROR 1062 (23000) at line 10166: Duplicate entry '252' for key 'PRIMARY'**

![image](https://github.com/lirantal/daloradius/assets/23372577/8b59441b-49bd-4c3e-a268-5e0309f1e64f)

Can someone please let me know how I can resolve it?, 
@lirantal

**Comment by prabath84** [comment]
I think I have solved the issue. However, I am not sure if this is completely correct or not.
I have removed the following highlighted entry from the maria-daloradius.sql

![image](https://github.com/lirantal/daloradius/assets/23372577/244de8f7-5ed4-4480-b6a5-97fd8a2f42e6)

Let me know your feedback.

**Comment by filippolauria** [comment]
Hi @prabath84 . Thanks for reaching out and contributing. The issue you reported has been resolved 3 days ago. Please, try repeating the installation steps with the most recent version of daloRADIUS.

**Comment by prabath84** [comment]
Hi @filippolauria : I have to go through the Installation steps in the (https://github.com/lirantal/daloradius/blob/master/doc/install/INSTALL.debian.md) today and raised this issue. 

Still not possible, go through the "mariadb -u raduser -p raddb < mariadb-daloradius.sql" step. 
So I have manually modified the    mariadb-daloradius.sql"  and removed the "252,6,'config_mail_testing',1"
executed the "mariadb -u raduser -p raddb < mariadb-daloradius.sql" step again. 
Finally, sql statement ran without any error from the command prompt. 

I want to know If you resolved it 3 days ago is if there are other issues.
What I have done today to resolve the sql statement is the correct way of doing.

**Comment by filippolauria** [comment]
The issue has already been resolved. As indicated in the subject, the duplicate key was 252. Deleting a record with the key 253 is pointless. Please ensure that you have the most updated installation files.
